---
- hosts: localhost
  vars:
    state: present
  tasks:
    - name: create backend using s3
      terraform:
        project_path: './'
        state: "{{ state }}"
        lock: yes
        backend_config:
          region: "ap-south-1"
          bucket: "jenkins-devops-poc-backend"
          key: "backend.tfstate"
          dynamodb_table: "my-backend-lock"